---
- name: Install Http server
  hosts: n2
  become: yes

  tasks:
  - name: Install HTTPD
    yum:
      name: httpd
      state: installed

  - name: Start Httpd
    service:
      name: htppd
      state: started

  - name: Enable Httpd
    service:
      name: htppd
      enabled: yes
...

